apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "oscal-controller.fullname" . }}
spec:
  selector:
    app: {{ include "oscal-controller.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: metrics
